In [1]:
import numpy as np

In [29]:
married = 1
divorced = 2
single = 3
#features
X = np.array([[50000, 200, married], [30000, 4, divorced], [35000, 1, married], [80000, 5, single]])
#classes
y = [1, 0, 1, 1]

In [14]:
new_customer = np.array([60000, 10, married])
print((X - new_customer)**2)
print(np.sum((X - new_customer)**2, axis=1)**0.5)

[[100000000       100         0]
 [900000000        36         1]
 [625000000        81         0]
 [400000000        25         4]]
[10000.005      30000.00061667 25000.00162    20000.000725  ]


In [30]:
#minmax scaling
#all features are on scale between 0 and 1

X_min, X_max = np.min(X, axis=0), np.max(X, axis=0)
(X - X_min) / (X_max - X_min)

array([[0.4       , 1.        , 0.        ],
       [0.        , 0.01507538, 0.5       ],
       [0.1       , 0.        , 0.        ],
       [1.        , 0.0201005 , 1.        ]])

In [41]:
#z score

X_mean = np.mean(X, axis=0)
X_std = np.std(X, axis=0)
print(X_std)

(X - X_mean) / X_std

instance = np.array([1000000, 3, married])

(instance - X_mean) / X_std


[1.94855716e+04 8.51718850e+01 8.29156198e-01]


array([48.81817276, -0.5811777 , -0.90453403])